name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
  workflow_dispatch:
    inputs:
      run_tests:
        description: 'Executar testes?'
        required: true
        default: 'true'
        type: boolean
      run_lint:
        description: 'Executar lint?'
        required: true
        default: 'true'
        type: boolean

jobs:
  checkout:
    name: Checkout do projeto
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  build:
    name: Build do projeto
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build com Maven
        run: mvn clean install

  package:
    name: Gerar pacote .jar
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gerar .jar com Maven
        run: mvn package

  deploy:
    name: Simulando Deploy
    runs-on: ubuntu-latest
    needs: [build, package]
    steps:
      - name: Mensagem de Deploy
        run: echo "Deploy realizado com sucesso"
