name: Lint and Test

on:
  workflow_call:

jobs:
  lint:
    name: Verificar estilo do código (Lint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Executar Lint (Checkstyle)
        run: mvn checkstyle:check

  test:
    name: Executar testes
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Executar testes
        run: mvn test